{
 "title": "App Dashboard",
 "description": "This dashboard collects metrics from app",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Model",
   "type": "timeseries",
   "description": "This shows model-service related metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(model_accuracy{container=\"app-api\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(prediction_requests_total[5m]))/sum(rate(flask_app_index_requests_total[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(prediction_requests_total[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(error_requests_total[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(correct_predictions[5m]))\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(incorrect_predictions[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration Metrics",
   "type": "timeseries",
   "description": "This shows the request duration to understand the response time distribution and overall performance monitoring",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(flask_app_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(flask_app_request_duration_seconds_summary_sum[5m])) / sum(rate(flask_app_request_duration_seconds_summary_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU_Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(cpu_usage{container=\"app-api\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(memory_usage{container=\"app-api\"})/(2^32)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}