# common.yml
---
- name: Install common dependencies
  hosts: all
  tasks:
  - name: Update cache
    become: true
    apt:
      update_cache: yes

  - name: Install common dependencies
    become: true
    apt:
      name: 
        - curl 
        - apt-transport-https 
        - ca-certificates 
        - software-properties-common 
        - gpg
        - gnupg
      state: present

  - name: Check if Docker is installed
    command: docker --version
    register: docker_check
    ignore_errors: true

  - name: Install Docker
    become: true
    apt:
      name: docker.io
      state: present
    when: docker_check.failed

  - name: Check if k3s is installed
    command: k3s --version
    register: k3s_check
    ignore_errors: true

  - name: Download k3s installer
    become: true
    shell: curl -sfL https://get.k3s.io -o /usr/local/bin/install-k3s.sh
    args: 
      creates: /usr/local/bin/install-k3s.sh
    when: k3s_check.failed

  - name: Set execute permissions for k3s installer
    become: true
    file:
      path: /usr/local/bin/install-k3s.sh
      mode: '0755'
    when: k3s_check.failed

  - name: Install k3s
    become: true
    shell: /usr/local/bin/install-k3s.sh
    when: k3s_check.failed