  # controller.yml
  ---
  - name: Setup kubernetes controller Minikube
    hosts: controller
    vars:
      master_node_ip: "192.168.56.2"
    
    tasks:
      - name: Install Docker
        become: true
        apt:
          name: docker.io
          state: present

      - name: Install Minikube
        become: true
        shell: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
        