# app.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app-api
        image: ghcr.io/release-engineering-4/app:main.main.latest
        ports:
        - containerPort: 8080
        env:
        - name: MODEL_URL
          value: "http://model-service:8080/predict"
---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app-serv
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  defaultBackend:
    service:
      name: app
      port:
        number: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mymonitor
  labels:
    release: myprom
spec:
  selector:
    matchLabels:
      app: app-serv
  endpoints:
    - interval: 30s 
# service.yml
---
apiVersion: v1
kind: Pod
metadata:
  name: model-service
  labels:
    app: model-service
spec:
  containers:
  - name: model-service
    image: ghcr.io/release-engineering-4/model-service:v0.0.3
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
  selector:
    app: model-service
  type:
    ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      