apiVersion: v1
kind: ConfigMap
metadata:
  name: rate-limit-config
  namespace: istio-system
data:
  config.yaml: |
    domain: app
    descriptors:
      - key: generic_key
        value: slowpath
        rate_limit:
          unit: minute
          requests_per_unit: 10
